# this file was generated by serverless-auto-swagger
docs = {
  "swagger": "2.0",
  "info": {
    "title": "API IA",
    "version": "1"
  },
  "paths": {
    "/": {
      "post": {
        "summary": "ia",
        "description": "",
        "operationId": "ia.post./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
}